sudo: required
services:
  - docker


before_install:
  - docker build -t ferozpuri/first-reactapp -f Dockerfile.dev .


script:
  - docker run ferozpuri/first-reactapp npm run test -- --coverage


deploy:
  provider: elsticbeanstalk
  region: "us-west-2"
  app: "docker-reactapp"
  env: "Docker-env"
  bucket_name: ""
  bucket_path: "docker-reactapp"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
